#!/bin/bash
# REV06: Wed Sep 13 20:17:40 WIB 2017
# START: Mon Sep  5 11:12:35 WIB 2016

# These are some command lines 
# Copyright (C) 2016-2017 http://RahmatM.Samik-Ibrahim.vLSM.org/
# This program is free script/software. This program is distributed in the hope 
# that it will be useful, but WITHOUT ANY WARRANTY; without even the implied 
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

XX="xx"
clear

for II in      \
    'systemctl list-unit-files | head -8; echo "(...)";systemctl list-unit-files| tail -8' \
    'systemd-analyze blame | wc -l; echo "===";systemd-analyze blame | head -15' \
    'systemctl --full  | wc -l; echo "===";systemctl --full  | head -10' \
    'systemctl list-units  | wc -l; echo "===";systemctl list-units  | head -10' \
    'systemctl list-units |grep .service|wc -l;echo "===";systemctl list-units|grep .service|head -10' \
    'systemctl list-units  | grep ssh.service' \
    'systemctl status ssh.service' \
    'systemctl is-enabled ssh' \
    'journalctl' \
    'journalctl -b' \

do
    COMMENT="RUNNING:  $II"
    SIZE=${#COMMENT}
    (( $SIZE > 80 )) && SIZE=80
    STR=$(eval printf "%0.s=" {1..$SIZE})
    echo "$STR"
    echo $COMMENT
    echo "$STR"
    eval $II
    echo ""; echo "*** Hit Anykey ***";
    [ "$1" = "$XX" ] || (read YY ; clear)
done

exit

