#!/bin/bash
# REV11: Mon Feb 12 19:47:23 WIB 2018
# REV01: Mon Jun 26 21:48:52 WIB 2017
# START: Mon Feb 13 20:22:22 WIB 2017

# R: This script is sorting files and preparing the demo.
#    Just run "bash a02-sort-n-prepare"

# Copyright (C) 2017-2018 http://RahmatM.Samik-Ibrahim.vLSM.org/
# This program is free script/software. This program is distributed in the hope 
# that it will be useful, but WITHOUT ANY WARRANTY; without even the implied 
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

PREFIX="^#.R:"
RESULT=`grep $PREFIX $0`
clear
if [[ $RESULT ]] ; then
   printf "\n[%11s]: %s\n" "`cut -c 1-11 <<< $0`" "$RESULT"
fi
echo ""
echo "================================================="
echo "Just run this script:"
echo "bash $0    (... for reset)"
echo "bash $0 xx (... for total reset)"
echo "Check and compare with:"
echo "ls -al"
echo "Do also:"
echo "bash a01-README"
echo "================================================="

HEAD="a" 
TMPHEAD="ZTMP"
START="0"
TMPSEQ="1000"
TESTDIR1=".TESTFROM"
TESTDIR2=".TESTBACKUP"
AWKPROG="$TESTDIR1/file.awk"
CPROGRAM="$TESTDIR1/program2.c"
TMPFILE=".thisfile.tx"
FILE1="$TESTDIR1/file1.txt"
FILE2="$TESTDIR1/file2.txt"
FILE3="$TESTDIR1/80x23.txt"
DEL="xx"

# check is "aXX-XXXXX" files exist.
for FF in ${HEAD}* ; do
   [ -e $FF ] && {
      NFILES=`ls ${HEAD}* | wc -l`
      FORMAT="%${#NFILES}.${#NFILES}d"
   } || { 
      echo "No $FF"
      exit
   }
done

# temporary rename "aXX-YYYYY" to "ZTMPXX-YYYYY"
SEQ=$TMPSEQ
for FF in ${HEAD}* ; do
   ((SEQ++))
   TMPNAME=`echo $FF | cut -d"-" -f2-`
   TMPNAME=`printf "${TMPHEAD}${FORMAT}-$TMPNAME" $SEQ`
   [[ $FF != $TMPNAME ]] && /bin/mv $FF $TMPNAME 
done

# rearrange back from "ZTMPXX-YYYYY" to "aXX-YYYYY".
SEQ=$START
for FF in ${TMPHEAD}* ; do
   ((SEQ++))
   NEWNAME=`echo $FF | cut -d"-" -f2-`
   NEWNAME=`printf "${HEAD}${FORMAT}-${NEWNAME}" $SEQ`
   [[ $FF != $NEWNAME ]] && /bin/mv $FF $NEWNAME 
   chmod 755 $NEWNAME
done
chmod 644 ${HEAD}*

# Cleaning
rm -rf $TESTDIR1 $TESTDIR2 $TMPFILE* .txt

[ "$1" = "$DEL" ] && exit 0

# ###############################################################
# Creating new Demo directories.
mkdir -p $TESTDIR1 $TESTDIR2
touch "$TESTDIR1/abcd 'xyz NNNN"
touch "$TESTDIR1/#wah , berkas * ini ^ aneh & ajaib"
touch "$TESTDIR1/[email anda : cicak@bin.kadal?!]"
touch "$TESTDIR1/x y z \" z y x"
touch "$TESTDIR1/x y z \" (z y) x"
touch "$TESTDIR1/x y z \" (z y)"
chmod -R 755 $TESTDIR1

# ###############################################################
# Demo progam for AWK
cat > $AWKPROG << NNNN
# REV01 Thu Feb 16 15:25:32 WIB 2017
# START Mon Sep  5 15:18:07 WIB 2016
BEGIN           { FS=":" 
                  print ""
                  print "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" }
END             { print "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" }
                { printf " %-20s  %5s  %5s \n", \$1,  \$3,  \$4 }
NNNN

# ###############################################################
# Demo for program C
cat > $CPROGRAM << NNNN
/* REV02 Fri Sep  8 21:17:45 WIB 2017
 * START Mon Feb 13 20:22:22 WIB 2017
 * (c) 2016-2017 Rahmat M. Samik-Ibrahim
 * This is a free software.
 */
#define LOOP1 400
#define LOOP2 1000000
#include <stdio.h>

void main() {
   int ii, jj, kk=0;
   for (ii=0;ii<LOOP1;ii++) {
      for (jj=0;jj<LOOP2;jj++) {
         kk = kk + ii;
      }
   }
   printf("Result=%d\n",kk);
}
NNNN

# Files for demo
# ###############################################################
cat > $TMPFILE << NNNN
This is line one
This is line two
This is line three
This is line four
This is line five
NNNN
# ###############################################################
cat > $FILE1 << NNNN
Potong Bebek Angsa, masak di kuali...
Nona minta dansa, dansa empat kali...
Sorong ke kiri, sorong ke kanan...
Lala lala lala lala la la la... 
NNNN
# ###############################################################
cat > $FILE2 << NNNN
Potong Bebek Angsa, masak di kuali...
Nona minta dansa, dansa empat kali...
Sorong ke kiri, Biak ke kanan...
Lala lala lala lala la Papua... 
NNNN
cat > $FILE3 << NNNN
01 START START START START START START START START START START START START START
12345678911234567892123456789312345678941234567895123456789612345678971234567898
         10        20        30        40        50        60        70       79

12345678911234567892123456789312345678941234567895123456789612345678971234567898

         10        20        30        40        50        60        70       79
12345678911234567892123456789312345678941234567895123456789612345678971234567898
09 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXX                           TEST FOR 80 x 23                           XXXXX

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
12345678911234567892123456789312345678941234567895123456789612345678971234567898
         10        20        30        40        50        60        70       79

         10        20        30        40        50        60        70       79
12345678911234567892123456789312345678941234567895123456789612345678971234567898
19 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

         10        20        30        40        50        60        70       79
12345678911234567892123456789312345678941234567895123456789612345678971234567898
23 END END END END  END END END END  END END END END END END END END END END END
NNNN
# ###############################################################

chmod 644 $AWKPROG $CPROGRAM $TXFILE $FILE1 $FILE2 $FILE3

exit 0

